#!/bin/bash
# Create two container, one for server, another for client
#
# CCCM Container:
#     Container name = cccm
#     Host name      = vm-cccm
#     Ssh  port map  = 2022

# VCM Container: 
#     Container name = vcm
#     Host name      = cm-vcm
#     Ssh  port map  = 2024
#

docker run -d --hostname=vm-vcm --name=vcm  -p 2022:22  chao123/soa-ecu
docker run -d --hostname=vm-cccm --name=cccm  -p 2024:22  chao123/soa-ecu
