#!/bin/bash

echo "You are trying to delete testing container vcm & cccm... "

ANS=no

read -p "Are you sure [yes/no] ? << " ANS

if [ $ANS != 'yes' ]
then
	echo "Cancel...."
else
	docker rm -f vcm
	docker rm -f cccm
	echo "Deleting........done"
fi

