name: Docker Image CI

on:
  push:
    branches: [ "main","soa_ecu" ]
  pull_request:
    branches: [ "main" ]

jobs:

    
  build:
     
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, x64]
    
    environment:
      name: someip-docker
      
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push someip-BASE Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./base/Dockerfile
        push: true
        tags: "chao123/someip-base:latest"

    - name: Build and push someip-CORE Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./someip-core/Dockerfile
        push: true
        tags: "chao123/someip-core:latest"

    - name: Build and push someip-USER Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./someip/Dockerfile
        push: true
        tags: "chao123/someip:latest"
        
