name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

    
  build:
     
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, x64]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: print user credential
      run: |
        echo "user:${{ secrets.DOCKER_USERNAME }} pass:${{ secrets.DOCKER_PASSWORD }}"
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the base someip Docker image
      run: docker build . --file base/Dockerfile --tag someip-base:lastest
      
    - name: Push the base someip Docker image
      run: docker push someip-base:lastest

    - name: Build the someip-core Docker image
      run: docker build . --file someip-core/Dockerfile --tag someip-core:lastest
    
    - name: Build the someip Docker image
      run: docker build . --file someip/Dockerfile --tag someip:lastest
