name: Docker Image CI

on:
  push:
    branches: [ "main","pb-sip" ]
  pull_request:
    branches: [ "main" ]

jobs:

    
  build:
     
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, x64]
    
    environment:
      name: someip-docker
      
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push pb-sip Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./protoc-someip-core/Dockerfile
        push: true
        tags: "chao123/pb-sip:latest"

        
