name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    - name: docker login
      uses: docker/login-action@v3.0.0
      with:
        username: touchao123@126.com
        password: 
    
  build:

    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, x64]

    steps:
    - name: Show files changed
    - uses: actions/checkout@v3
    
    - name: Build the base someip Docker image
      run: docker build . --file base/Dockerfile --tag someip-base:lastest
      
    - name: Push the base someip Docker image
      run: docker push someip-base:lastest

    - name: Build the someip-core Docker image
      run: docker build . --file someip-core/Dockerfile --tag someip-core:lastest
    
    - name: Build the someip Docker image
      run: docker build . --file someip/Dockerfile --tag someip:lastest
